"""add_vibe_to_swipes

Revision ID: 175aaf8c90af
Revises: 4cc4c859ea84
Create Date: 2026-07-07 11:42:00.755128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175aaf8c90af'
down_revision: Union[str, None] = '4cc4c859ea84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipes', sa.Column('vibe', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swipes', 'vibe')
    # ### end Alembic commands ###
