"""add_max_closing_hour_to_restaurants

Revision ID: 32997e5cb95b
Revises: ed7b20955eb7
Create Date: 2026-07-03 22:22:56.137487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32997e5cb95b'
down_revision: Union[str, None] = 'ed7b20955eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('max_closing_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'max_closing_hour')
    # ### end Alembic commands ###
