"""add_gambler_count_to_users

Revision ID: 570e0ae9d8e3
Revises: dd20c0e18640
Create Date: 2026-07-04 16:16:34.688785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570e0ae9d8e3'
down_revision: Union[str, None] = 'dd20c0e18640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gambler_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gambler_count')
    # ### end Alembic commands ###
