"""add_user_status_cuisine_transport

Revision ID: 872ef2fdbcd8
Revises: 82bf73d8e663
Create Date: 2026-06-28 22:03:43.049220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872ef2fdbcd8'
down_revision: Union[str, None] = '82bf73d8e663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='onboarding', nullable=False))
    op.add_column('users', sa.Column('cuisine_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('transport_modes', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'transport_modes')
    op.drop_column('users', 'cuisine_preferences')
    op.drop_column('users', 'status')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
