"""add_tournament_nudge_fields_to_saves

Revision ID: c727d49e318d
Revises: b84cadf5d8d1
Create Date: 2026-07-03 20:05:54.805594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c727d49e318d'
down_revision: Union[str, None] = 'b84cadf5d8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saves', sa.Column('picked_at', sa.DateTime(), nullable=True))
    op.add_column('saves', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    op.add_column('saves', sa.Column('nudge_dismissed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saves', 'nudge_dismissed')
    op.drop_column('saves', 'snoozed_until')
    op.drop_column('saves', 'picked_at')
    # ### end Alembic commands ###
