"""add_rating_at_visit_to_visits

Revision ID: dd20c0e18640
Revises: 32997e5cb95b
Create Date: 2026-07-04 16:07:49.422353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd20c0e18640'
down_revision: Union[str, None] = '32997e5cb95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('rating_at_visit', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'rating_at_visit')
    # ### end Alembic commands ###
