"""add_created_at_to_restaurants

Revision ID: ed7b20955eb7
Revises: c727d49e318d
Create Date: 2026-07-03 20:54:25.303371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7b20955eb7'
down_revision: Union[str, None] = 'c727d49e318d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'created_at')
    # ### end Alembic commands ###
