"""add_restaurant_review_count_tags_neighbourhood_image_emoji

Revision ID: fa871a610192
Revises: 872ef2fdbcd8
Create Date: 2026-06-28 22:48:46.767157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa871a610192'
down_revision: Union[str, None] = '872ef2fdbcd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('neighbourhood', sa.String(length=120), nullable=True))
    op.add_column('restaurants', sa.Column('image_emoji', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image_emoji')
    op.drop_column('restaurants', 'neighbourhood')
    op.drop_column('restaurants', 'tags')
    op.drop_column('restaurants', 'review_count')
    # ### end Alembic commands ###
